piniu_cart:
    resource: "@PiniuCartBundle/Resources/config/routing.yml"
    prefix:   /

piniu_users:
    resource: "@PiniuUsersBundle/Resources/config/routing.yml"
    prefix:   /

piniu_pages:
    resource: "@PiniuPagesBundle/Resources/config/routing.yml"
    prefix:   /

piniu_products:
    resource: "@PiniuProductsBundle/Resources/config/routing.yml"
    prefix:   /