<?php

namespace Piniu\ProductsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAll() {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p', 'c')
           ->leftJoin('p.category', 'c');

        return $qb->getQuery()->getResult();
    }

    public function findByCategory($categoryId) {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p', 'c')
           ->leftJoin('p.category', 'c')
           ->where($qb->expr()->eq('c.id', $categoryId));

        return $qb->getQuery()->getResult();
    }

    public function findOneById($id) {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p', 'c')
           ->leftJoin('p.category', 'c')
           ->where($qb->expr()->eq('p.id', $id));

        return $qb->getQuery()->getSingleResult();
    }

    public function findByIds($ids) {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
           ->where($qb->expr()->in('p.id', $ids));

        return $qb->getQuery()->getResult();
    }
}
