<?php

namespace Piniu\ProductsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getAllProducts() {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'c')
            ->leftJoin('p.category', 'c');

        return $qb->getQuery()
            ->getResult();
    }

    public function getAllProductsByCategory($categoryId) {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'c')
            ->leftJoin('p.category', 'c');

        $qb->where($qb->expr()->eq('c.id', $categoryId));

        return $qb->getQuery()
            ->getResult();
    }

    public function getProductById($id) {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'c')
            ->leftJoin('p.category', 'c');

        $qb->where($qb->expr()->eq('p.id', $id));

        return $qb->getQuery()
            ->getSingleResult();
    }
}
