piniu_users_login:
    pattern:  /login
    defaults: { _controller: PiniuUsersBundle:Security:login }

piniu_users_login_check:
    pattern:  /login_check

piniu_users_logout:
    pattern:  /logout

piniu_users_register:
    path:     /register
    defaults: { _controller: PiniuUsersBundle:Security:register }

piniu_users_create:
    path:     /register/create
    defaults: { _controller: PiniuUsersBundle:Security:create }