parameters:
#    piniu_users.example.class: Piniu\UsersBundle\Example

services:
#    piniu_users.example:
#        class: %piniu_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
